<?php

return [
    'structures' => [
        [
            'ID' => 1,
            'structure' => 'Ideal_Part',
            'name' => 'Страницы',
            'isShow' => 1,
            'hasTable' => true,
            'startName' => 'Главная',
            'url' => '',
        ],
        [
            'ID' => 2,
            'structure' => 'Ideal_User',
            'name' => 'Пользователи',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 3,
            'structure' => 'Ideal_DataList',
            'name' => 'Справочники',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 4,
            'structure' => 'Ideal_Service',
            'name' => 'Сервис',
            'isShow' => 1,
            'hasTable' => false,
        ],
        [
            'ID' => 5,
            'structure' => 'Ideal_Tag',
            'name' => 'Теги',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 6,
            'structure' => 'Ideal_News',
            'name' => 'Новости',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 7,
            'structure' => 'Ideal_Order',
            'name' => 'Заказы с сайта',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 8,
            'structure' => 'Ideal_Error404',
            'name' => 'Ошибки 404',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 9,
            'structure' => 'Ideal_Acl',
            'name' => 'Права пользователей',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 10,
            'structure' => 'Ideal_UserGroup',
            'name' => 'Группы пользователей',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 11,
            'structure' => 'Ideal_Log',
            'name' => 'Лог администраторов',
            'isShow' => 0,
            'hasTable' => true,
        ],
    ],
    'addons' => [
        [
            'ID' => 1,
            'structure' => 'Ideal_Page',
            'name' => 'Текст',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 2,
            'structure' => 'Ideal_Photo',
            'name' => 'Фотогалерея',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 3,
            'structure' => 'Ideal_PhpFile',
            'name' => 'PHP-файл',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 4,
            'structure' => 'Ideal_SiteMap',
            'name' => 'Карта сайта',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 5,
            'structure' => 'Ideal_YandexSearch',
            'name' => 'Яндекс.Поиск',
            'isShow' => 1,
            'hasTable' => true,
        ],
    ],
    // нужно только для проверки целостности
    'mediums' => [
        [
            'ID' => 1,
            'structure' => 'Ideal_AddonList',
            'name' => 'Связи для аддонов',
            'hasTable' => true,
        ],
        [
            'ID' => 2,
            'structure' => 'Ideal_StructureList',
            'name' => 'Связи для структур',
            'hasTable' => true,
        ],
        [
            'ID' => 3,
            'structure' => 'Ideal_TagList',
            'name' => 'Связи для тегов',
            'hasTable' => true,
        ],
        [
            'ID' => 4,
            'structure' => 'Ideal_TemplateList',
            'name' => 'Связи для шаблонов',
            'hasTable' => true,
        ],
        [
            'ID' => 5,
            'structure' => 'Ideal_UserGroupList',
            'name' => 'Связи для групп пользователей',
            'hasTable' => true,
        ],
        [
            'ID' => 6,
            'structure' => 'Ideal_UserList',
            'name' => 'Связи для пользователей',
            'hasTable' => true,
        ],
    ],
    'services' => [
        [
            'ID' => 'Ideal_Acl',
            'structure' => 'Ideal_Service',
            'name' => 'Права доступа',
            'pos' => 90,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_Backup',
            'structure' => 'Ideal_Service',
            'name' => 'Резервные копии',
            'pos' => 50,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_CheckDb',
            'structure' => 'Ideal_Service',
            'name' => 'Проверка целостности',
            'pos' => 30,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_Cron',
            'structure' => 'Ideal_Service',
            'name' => 'Cron',
            'pos' => 100,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_Error404',
            'structure' => 'Ideal_Service',
            'name' => '404 ошибки',
            'pos' => 80,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_Redirect',
            'structure' => 'Ideal_Service',
            'name' => 'Редирект',
            'pos' => 50,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_SiteData',
            'structure' => 'Ideal_Service',
            'name' => 'Настройки',
            'pos' => 20,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_SiteMap',
            'structure' => 'Ideal_Service',
            'name' => 'Карта сайта',
            'pos' => 60,
            'info' => '',
        ],
        [
            'ID' => 'Ideal_YandexTurboPage',
            'structure' => 'Ideal_Service',
            'name' => 'Яндекс Турбо-страницы',
            'pos' => 110,
            'info' => '',
        ],
    ],
];
