<?php

return [
    'structures' => [
        [
            'ID' => 1,
            'structure' => 'Ideal_Part',
            'name' => 'Страницы',
            'isShow' => 1,
            'hasTable' => true,
            'startName' => 'Главная',
            'url' => '',
        ],
        [
            'ID' => 2,
            'structure' => 'Ideal_User',
            'name' => 'Пользователи',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 3,
            'structure' => 'Ideal_DataList',
            'name' => 'Справочники',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 4,
            'structure' => 'Ideal_Service',
            'name' => 'Сервис',
            'isShow' => 1,
            'hasTable' => false,
        ],
        [
            'ID' => 5,
            'structure' => 'Ideal_Tag',
            'name' => 'Теги',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 6,
            'structure' => 'Ideal_News',
            'name' => 'Новости',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 7,
            'structure' => 'Ideal_Order',
            'name' => 'Заказы с сайта',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 8,
            'structure' => 'Ideal_Error404',
            'name' => 'Ошибки 404',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 9,
            'structure' => 'Ideal_Acl',
            'name' => 'Права пользователей',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 10,
            'structure' => 'Ideal_UserGroup',
            'name' => 'Группы пользователей',
            'isShow' => 0,
            'hasTable' => true,
        ],
        [
            'ID' => 11,
            'structure' => 'Ideal_Log',
            'name' => 'Лог администраторов',
            'isShow' => 0,
            'hasTable' => true,
        ],
    ],
    'addons' => [
        [
            'ID' => 1,
            'structure' => 'Ideal_Page',
            'name' => 'Текст',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 2,
            'structure' => 'Ideal_Photo',
            'name' => 'Фотогалерея',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 3,
            'structure' => 'Ideal_PhpFile',
            'name' => 'PHP-файл',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 4,
            'structure' => 'Ideal_SiteMap',
            'name' => 'Карта сайта',
            'isShow' => 1,
            'hasTable' => true,
        ],
        [
            'ID' => 5,
            'structure' => 'Ideal_YandexSearch',
            'name' => 'Яндекс.Поиск',
            'isShow' => 1,
            'hasTable' => true,
        ],
    ],
];
